# Generated by Django 5.1.2 on 2025-01-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shop_id',
            field=models.CharField(max_length=255),
        ),
    ]
