# Generated by Django 5.1.2 on 2025-01-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0002_alter_booking_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shop_id',
            field=models.CharField(default='Unknown Shop', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_id',
            field=models.CharField(default='Unknown User', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_model',
            field=models.CharField(default='Unknown Model', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(default='Unknown Number', max_length=50),
        ),
    ]
