# Generated by Django 5.1.2 on 2025-02-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
