# Generated by Django 5.1.2 on 2025-02-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorSide', '0002_alter_bill_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='booking_user_id',
            field=models.CharField(default='UNKNOWN_BOOKING_USER', max_length=255),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='bill',
            name='entry_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user_id',
            field=models.CharField(default='UNKNOWN_USER', max_length=255),
        ),
    ]
