# Generated by Django 5.1.2 on 2025-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentWallet', '0002_alter_document_options_alter_document_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterField(
            model_name='document',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User ID'),
        ),
    ]
